#Camunda config
camunda.bpm:
  admin-user:
    id: admin
    password: admin
    firstName: Admin
  filter:
    create: All tasks

#Processes folder path
processes:
  path: processes

spring:
  data:
    mongodb:
      database: maas
      host: localhost
      port: 27018
      auto-index-creation: true